
default: &default
  adapter: postgresql
  encoding: unicode

  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  template: template0
development:
  <<: *default
  database: personal_records_development


test:
  <<: *default
  database: personal_records_test


production:
  <<: *default
  database: personal_records_production
  username: personal_records
  password: <%= ENV['PERSONAL_RECORDS_DATABASE_PASSWORD'] %>
